# Generated by Django 5.2.7 on 2026-04-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_memo_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AlterField(
            model_name='post',
            name='memo',
            field=models.TextField(blank=True),
        ),
    ]
